;; extends

;; Keywords
(("use"     @keyword) (#set! conceal  "󰋺"))
(("mod"     @keyword) (#set! conceal  ""))
(("pub"     @keyword) (#set! conceal  ""))
(("unsafe"  @keyword) (#set! conceal  ""))
(("type"    @keyword) (#set! conceal  ""))
(("impl"    @keyword) (#set! conceal  "󱉯"))
(("struct"  @keyword) (#set! conceal  ""))
(("enum"    @keyword) (#set! conceal  ""))
(("trait"   @keyword) (#set! conceal ""))
(("fn"      @keyword) (#set! conceal "󰊕"))
(("return"  @keyword) (#set! conceal ""))
(("const"   @keyword) (#set! conceal ""))
(("static"  @keyword) (#set! conceal ""))
; (("where"   @keyword) (#set! conceal ""))
; (("let"     @keyword) (#set! conceal ""))
; (("for"     @keyword) (#set! conceal ""))
; (("while"   @keyword) (#set! conceal ""))
; (("loop"    @keyword) (#set! conceal ""))
