if not vim.filetype then return end

vim.filetype.add({
  extension = {
    lock = 'yaml',
  },
  filename = {
    ['NEOGIT_COMMIT_EDITMSG'] = 'NeogitCommitMessage',
    ['launch.json'] = 'jsonc',
    ['Makefile.toml'] = 'cargo-make',
    ['Podfile'] = 'ruby',
    ['.vimrc.local'] = 'vim',
    ['rebar.config'] = 'erlang',
    ['.env'] = 'config',
  },
  pattern = {
    ['.*%.astro'] = 'astro',
    ['.*%.sld'] = 'slide',
    ['.*%.graphql'] = 'graphql',
    ['.*%.gql'] = 'graphql',
    ['.*%.conf'] = 'conf',
    ['.*%.theme'] = 'conf',
    ['.*%.gradle'] = 'groovy',
    ['.*%.bkp'] = 'haskell',
    ['.*%.csv'] = 'csv',
    ['.*%.dat'] = 'csv',
    ['.*%.tsv'] = 'csv',
    ['.*%.tab'] = 'csv',
    ['.*%.info'] = 'info',
    ['.*%.app'] = 'erlang',
    ['.*%.xrl'] = 'erlang',
    ['.*%.escript'] = 'erlang',
    ['.*%.yaws'] = 'erlang',
    ['.*%.js.map'] = 'json',
    ['.*%.app.src'] = 'erlang',
    ['.*%.tmux%..conf'] = 'tmux',
    ['.*%.gitsendmail%..*'] = 'gitsendmail',
    ['[jt]sconfig.*.json'] = 'jsonc',
    ['req.*.txt'] = 'config',
  },
})
