return {
  packer = { active = true },
  -- debug
  dap = { active = true },
  dap_ui = { active = true },
  dap_install = { active = true },
  osv = { active = false },
  nvim_dap_virtual_text = { active = true },
  -- lsp
  lspconfig = { active = true },
  lsp_installer = { active = true },
  fix_cursorhold = { active = true },
  nlsp = { active = true },
  null_ls = { active = true },
  lightbulb = { active = false },
  symbols_outline = { active = false },
  bqf = { active = false },
  trouble = { active = true },
  rust_tools = { active = true },
  schemastore = { active = true },
  lsp_signature = { active = true },
  spellsitter = { active = true },
  -- treesitter
  treesitter = { active = true },
  playground = { active = true },
  autopairs = { active = true },
  rainbow = { active = false },
  autotag = { active = true },
  matchup = { active = false },
  -- editor
  ajk = { active = true },
  easy_align = { active = true },
  cool = { active = true },
  surround = { active = true },
  colorizer = { active = true },
  kommentary = { active = true },
  dial = { active = true },
  fold_cycle = { active = false },
  cursorword = { active = false },
  surround_funk = { active = true },
  better_diagraphs = { active = true },
  -- tools
  fterm = { active = true },
  far = { active = true },
  bookmarks = { active = false },
  undotree = { active = true },
  project = { active = true },
  diffview = { active = false },
  structlog = { active = true },
  bbye = { active = true },
  neoclip = { active = true },
  dressing = { active = true },
  auto_session = { active = true },
  impatient = { active = true },
  hop = { active = true },
  telescope = { active = true },
  telescope_fzf = { active = true },
  telescope_ui_select = { active = true },
  telescope_tmux = { active = true },
  telescope_frecency = { active = true },
  telescope_dap = { active = true },
  telescope_file_browser = { active = true },
  -- TODO: handle these later
  glow = { active = false },
  doge = { active = false },
  dadbod = { active = false },
  restconsole = { active = false },
  markdown_preview = { active = true },
  -- ui
  nvimtree = { active = true },
  dashboard = { active = true },
  statusline = { active = true },
  bufferline = { active = true },
  devicons = { active = true },
  git_signs = { active = true },
  indent_line = { active = true },
  nvim_notify = { active = true },
  -- completion
  which_key = { active = true },
  plenary = { active = true },
  popup = { active = true },
  cmp = { active = true },
  vsnip = { active = true },
  emmet = { active = true },
  friendly_snippets = { active = true },
}
