local vim = vim
local cmd = vim.cmd

cmd('autocmd ColorScheme * highlight clear SignColumn')
cmd('autocmd ColorScheme * highlight Normal ctermbg=NONE guibg=NONE')
cmd('hi LineNr ctermbg=NONE guibg=NONE ')
cmd('hi Comment cterm=italic')
cmd('hi clear LspDiagnosticsDefaultError')
cmd('hi clear LspDiagnosticsDefaultWarning')
cmd('hi clear LspDiagnosticsDefaultHint')
cmd('hi clear LspDiagnosticsDefaultInformation')
cmd('hi link LspDiagnosticsVirtualTextError ErrorMsg')
cmd('hi link LspDiagnosticsVirtualTextWarning ErrorMsg')
cmd('hi link LspDiagnosticsVirtualTextHint ErrorMsg')
cmd('hi link LspDiagnosticsVirtualTextInformation ErrorMsg')
cmd('hi link LspDiagnosticsFloatingError NormalFloat')
cmd('hi link LspDiagnosticsFloatingWarning NormalFloat')
cmd('hi link LspDiagnosticsFloatingHint NormalFloat')
cmd('hi link LspDiagnosticsFloatingInformation NormalFloat')
cmd('hi link LspDiagnosticsSignError ErrorMsg')
cmd('hi link LspDiagnosticsSignWarning ErrorMsg')
cmd('hi link LspDiagnosticsSignHint ErrorMsg')
cmd('hi link LspDiagnosticsSignInformation ErrorMsg')
cmd('hi clear LspDiagnosticsUnderlineError')
cmd('hi clear LspDiagnosticsUnderlineWarning')
cmd('hi clear LspDiagnosticsUnderlineHint')
cmd('hi clear LspDiagnosticsUnderlineInformation')
cmd('hi link LspDiagnosticsUnderlineError SpellBad')
cmd('hi link LspDiagnosticsUnderlineWarning SpellBad')
cmd('hi link LspDiagnosticsUnderlineHint SpellBad')
cmd('hi link LspDiagnosticsUnderlineInformation SpellBad')
