return {
  -- SANE defaults
  SANE = { active = false },
  -- debug
  debug = { active = false },
  debug_ui = { active = false },
  dap_install = { active = false },
  osv = { active = false },
  -- lsp
  lspconfig = { active = true },
  lsp_installer = { active = true },
  fix_cursorhold = { active = true },
  nlsp= { active = true },
  null_ls = { active = true },
  saga = { active = false },
  lightbulb = { active = false },
  symbols_outline = { active = false },
  bqf = { active = true },
  trouble = { active = true },
  nvim_lint = { active = false },
  formatter = { active = false },
  lsp_ts_utils = { active = false },
  -- treesitter
  treesitter = { active = true },
  playground = { active = true },
  rainbow = { active = true },
  autotag = { active = true },
  matchup = { active = false },
  autopairs = { active = true },
  -- editor
  fold_cycle = { active = true },
  ajk = { active = true },
  easy_align = { active = true },
  cool = { active = true },
  delimitmate = { active = false },
  eft = { active = false },
  cursorword = { active = false },
  surround = { active = true },
  dial = { active = true },
  colorizer = { active = true },
  kommentary = { active = true },
  -- tools
  fterm = { active = true },
  far = { active = true },
  bookmarks = { active = true },
  undotree = { active = true },
  fugitive = { active = false },
  project = { active = false },
  diffview = { active = false },
  -- TODO: handle these later
  glow = { active = false },
  doge = { active = false },
  dadbod = { active = false },
  restconsole = { active = false },
  markdown_preview = { active = false },
  -- aesth
  tree = { active = true },
  dashboard = { active = true },
  statusline = { active = true },
  bufferline = { active = true },
  devicons = { active = true },
  git_signs = { active = false },
  indent_line = { active = false },
  -- completion
  which_key = { active = true },
  plenary = { active = true },
  popup = { active = true },
  telescope = { active = true },
  compe = { active = true },
  vsnip = { active = true },
  emmet = { active = false },
  friendly_snippets = { active = true },
  telescope_fzy = { active = false },
  telescope_project = { active = false },
  telescope_media_files = { active = false },
}
