return function()
  local nnoremap = rvim.nnoremap
  nnoremap("<Leader>ga", ":Git fetch --all<CR>")
  nnoremap("<Leader>gA", ":Git blame<CR>")
  nnoremap("<Leader>gb", ":GBranches<CR>")
  nnoremap("<Leader>gcm", ":Git commit<CR>")
  nnoremap("<Leader>gca", ":Git commit --amend -m ")
  nnoremap("<Leader>gC", ":Git checkout -b ")
  nnoremap("<Leader>gd", ":Git diff<CR>")
  nnoremap("<Leader>gD", ":Gdiffsplit<CR>")
  nnoremap("<Leader>gh", ":diffget //3<CR>")
  nnoremap("<Leader>gi", ":Git init<CR>")
  nnoremap("<Leader>gk", ":diffget //2<CR>")
  nnoremap("<Leader>gl", ":Git log<CR>")
  nnoremap("<Leader>ge", ":Git push<CR>")
  nnoremap("<Leader>gp", ":Git poosh<CR>")
  nnoremap("<Leader>gP", ":Git pull<CR>")
  nnoremap("<Leader>gr", ":GRemove<CR>")
  nnoremap("<Leader>gs", ":G<CR>")
end
