return {
  commits = {
    autopairs = "784398a8f184431fd4329f20b0e4f52e87707bbd",
    gitsigns = "1d1f043acf025f919b8dd12bb672569109c7f099",
    null_ls = "3059dc761b27c4c836f88879c460cd7a989caa47",
    nvim_cmp = "13d64460cba64950aff41e230cc801225bd9a3e2",
    nvim_lsp_installer = "c95ffd31428da0abaffa2459c0231fa9971fcbaa",
    nvim_lspconfig = "19a21d5a8681f721c584125a920d4cbeda1c80cc",
    nvim_tree = "2e1f82d8c0c57cbc2bfdc041a3aff26947559a1e",
    nvim_treesitter = "2298a7584414af40a6a09cbe72a81175382992c7",
    schemastore = "c0c11c832fa812174cd196c723b97c493f528b5c",
  },
  -- SANE defaults
  SANE = { active = false },
  packer = { active = true },
  -- debug
  dap = { active = true },
  dap_ui = { active = true },
  dap_install = { active = true },
  osv = { active = false },
  nvim_dap_virtual_text = { active = true },
  -- lsp
  lspconfig = { active = true },
  lsp_installer = { active = true },
  fix_cursorhold = { active = true },
  nlsp = { active = true },
  null_ls = { active = true },
  lightbulb = { active = false },
  symbols_outline = { active = false },
  bqf = { active = false },
  trouble = { active = false },
  renamer = { active = true },
  rust_tools = { active = true },
  schemastore = { active = true },
  lsp_signature = { active = true },
  spellsitter = { active = true },
  -- treesitter
  treesitter = { active = true },
  playground = { active = true },
  autopairs = { active = true },
  rainbow = { active = false },
  autotag = { active = true },
  matchup = { active = false },
  -- editor
  ajk = { active = true },
  easy_align = { active = true },
  cool = { active = true },
  surround = { active = true },
  colorizer = { active = true },
  kommentary = { active = true },
  dial = { active = true },
  fold_cycle = { active = false },
  cursorword = { active = false },
  -- tools
  fterm = { active = true },
  far = { active = true },
  bookmarks = { active = false },
  undotree = { active = true },
  project = { active = true },
  diffview = { active = false },
  structlog = { active = true },
  bbye = { active = true },
  neoclip = { active = true },
  -- TODO: handle these later
  glow = { active = false },
  doge = { active = false },
  dadbod = { active = false },
  restconsole = { active = false },
  markdown_preview = { active = true },
  -- ui
  nvimtree = { active = true },
  dashboard = { active = true },
  statusline = { active = true },
  bufferline = { active = true },
  devicons = { active = true },
  git_signs = { active = true },
  indent_line = { active = true },
  fidget = { active = true },
  -- completion
  which_key = { active = true },
  vim_which_key = { active = false },
  plenary = { active = true },
  popup = { active = true },
  cmp = { active = true },
  vsnip = { active = true },
  emmet = { active = true },
  friendly_snippets = { active = true },
  telescope = { active = true },
  telescope_fzf = { active = true },
  telescope_ui_select = { active = true },
  telescope_tmux = { active = true },
  telescope_frecency = { active = true },
  telescope_dap = { active = true },
  telescope_file_browser = { active = true },
}
