return {
  commits = {
    autopairs = "fba2503bd8cd0d8861054523aae39c4ac0680c07",
    gitsigns = "4a2d30f5fb77750c7a42be9bb58a9cc2c6c7f31d",
    null_ls = "59067dae4bf2367eb06326e419c23353722ecbec",
    nvim_cmp = "d93104244c3834fbd8f3dd01da9729920e0b5fe7",
    nvim_lsp_installer = "88e44bbbe2e03523e08f2bd3c9a954675bc438f4",
    nvim_lspconfig = "c51096481dc13193991571b7132740d762902355",
    nvim_tree = "2dfed89af7724f9e71d2fdbe3cde791a93e9b9e0",
    nvim_treesitter = "56634f49ab3d8122153c8c5582c581fb6a6af075",
    -- nvim_treesitter = "620cc936ad6b26c59bb2d888b3890bb8d06c50c7",
  },
  -- SANE defaults
  SANE = { active = false },
  packer = { active = true },
  -- debug
  dap = { active = false },
  dap_ui = { active = false },
  dap_install = { active = false },
  osv = { active = false },
  -- lsp
  lspconfig = { active = true },
  lsp_installer = { active = true },
  fix_cursorhold = { active = false },
  nlsp = { active = true },
  null_ls = { active = true },
  lightbulb = { active = false },
  symbols_outline = { active = false },
  bqf = { active = false },
  trouble = { active = false },
  -- treesitter
  treesitter = { active = true },
  playground = { active = false },
  autopairs = { active = false },
  rainbow = { active = false },
  autotag = { active = false },
  matchup = { active = false },
  -- editor
  ajk = { active = true },
  easy_align = { active = false },
  cool = { active = false },
  surround = { active = false },
  colorizer = { active = false },
  kommentary = { active = false },
  dial = { active = false },
  fold_cycle = { active = false },
  cursorword = { active = false },
  -- tools
  fterm = { active = false },
  far = { active = false },
  bookmarks = { active = false },
  undotree = { active = false },
  fugitive = { active = false },
  project = { active = false },
  diffview = { active = false },
  structlog = { active = false },
  -- TODO: handle these later
  glow = { active = false },
  doge = { active = false },
  dadbod = { active = false },
  restconsole = { active = false },
  markdown_preview = { active = false },
  -- aesth
  nvimtree = { active = true },
  dashboard = { active = false },
  statusline = { active = true },
  bufferline = { active = true },
  devicons = { active = false },
  git_signs = { active = true },
  indent_line = { active = false },
  -- completion
  which_key = { active = true },
  plenary = { active = false },
  popup = { active = false },
  cmp = { active = false },
  vsnip = { active = false },
  emmet = { active = false },
  friendly_snippets = { active = false },
  telescope = { active = true },
  telescope_fzf = { active = true },
  telescope_ui_select = { active = true },
  telescope_tmux = { active = true },
  telescope_frecency = { active = true },
}
