return {
  commits = {
    autopairs = "fba2503bd8cd0d8861054523aae39c4ac0680c07",
    gitsigns = "4a2d30f5fb77750c7a42be9bb58a9cc2c6c7f31d",
    null_ls = "2ae4a5e2e2b35716c44c104ef1afa35ecb40c444",
    nvim_cmp = "d93104244c3834fbd8f3dd01da9729920e0b5fe7",
    nvim_lsp_installer = "88e44bbbe2e03523e08f2bd3c9a954675bc438f4",
    nvim_lspconfig = "c51096481dc13193991571b7132740d762902355",
    nvim_tree = "2dfed89af7724f9e71d2fdbe3cde791a93e9b9e0",
    nvim_treesitter = "5e3a93f365094eb7c6ed2a9ef0a6277da3b53201",
  },
  -- SANE defaults
  SANE = { active = false },
  packer = { active = true },
  -- debug
  dap = { active = false },
  dap_ui = { active = false },
  dap_install = { active = false },
  osv = { active = false },
  -- lsp
  lspconfig = { active = true },
  lsp_installer = { active = true },
  fix_cursorhold = { active = true },
  nlsp = { active = true },
  null_ls = { active = true },
  lightbulb = { active = false },
  symbols_outline = { active = false },
  bqf = { active = false },
  trouble = { active = false },
  renamer = { active = false },
  -- treesitter
  treesitter = { active = true },
  playground = { active = true },
  autopairs = { active = true },
  rainbow = { active = false },
  autotag = { active = false },
  matchup = { active = false },
  -- editor
  ajk = { active = true },
  easy_align = { active = true },
  cool = { active = true },
  surround = { active = true },
  colorizer = { active = true },
  kommentary = { active = true },
  dial = { active = true },
  fold_cycle = { active = false },
  cursorword = { active = false },
  -- tools
  fterm = { active = true },
  far = { active = true },
  bookmarks = { active = false },
  undotree = { active = true },
  fugitive = { active = false },
  project = { active = true },
  diffview = { active = false },
  structlog = { active = true },
  bbye = { active = true },
  -- TODO: handle these later
  glow = { active = false },
  doge = { active = false },
  dadbod = { active = false },
  restconsole = { active = false },
  markdown_preview = { active = false },
  -- ui
  nvimtree = { active = true },
  dashboard = { active = true },
  statusline = { active = true },
  bufferline = { active = true },
  devicons = { active = true },
  git_signs = { active = true },
  indent_line = { active = true },
  -- completion
  which_key = { active = true },
  vim_which_key = { active = false },
  plenary = { active = true },
  popup = { active = true },
  cmp = { active = true },
  vsnip = { active = true },
  emmet = { active = true },
  friendly_snippets = { active = true },
  telescope = { active = true },
  telescope_fzf = { active = true },
  telescope_ui_select = { active = true },
  telescope_tmux = { active = true },
  telescope_frecency = { active = true },
}
