return {
  commits = {
    null_ls = "b75effe6cb304e97901289f3f2e8d2ba77c7b752",
    nvim_lspconfig = "c0310ab4c7ac864031bbf82b07809b36df54a9d2",
    nvim_lsp_installer = "3805f06d3e5b25996563fd9740a90014948bc31a",
    autopairs = "fba2503bd8cd0d8861054523aae39c4ac0680c07",
    nvimtree = "5d8453dfbd34ab00cb3e8ce39660f9a54cdd35f3",
    -- nvimtree = "e842f088847c98da59e14eb543bde11c45c87ef7",
  },
  -- SANE defaults
  SANE = { active = false },
  packer = { active = true },
  -- debug
  dap = { active = false },
  dap_ui = { active = false },
  dap_install = { active = false },
  osv = { active = false },
  -- lsp
  lspconfig = { active = true },
  lsp_installer = { active = true },
  fix_cursorhold = { active = false },
  nlsp = { active = true },
  null_ls = { active = true },
  lightbulb = { active = false },
  symbols_outline = { active = false },
  bqf = { active = false },
  trouble = { active = false },
  -- treesitter
  treesitter = { active = true },
  playground = { active = true },
  autopairs = { active = true },
  rainbow = { active = false },
  autotag = { active = true },
  matchup = { active = true },
  -- editor
  ajk = { active = true },
  easy_align = { active = true },
  cool = { active = true },
  surround = { active = true },
  colorizer = { active = true },
  kommentary = { active = true },
  dial = { active = true },
  fold_cycle = { active = false },
  cursorword = { active = false },
  -- tools
  fterm = { active = true },
  far = { active = true },
  bookmarks = { active = false },
  undotree = { active = true },
  fugitive = { active = false },
  project = { active = true },
  diffview = { active = false },
  structlog = { active = true },
  -- TODO: handle these later
  glow = { active = false },
  doge = { active = false },
  dadbod = { active = false },
  restconsole = { active = false },
  markdown_preview = { active = false },
  -- aesth
  nvimtree = { active = true },
  dashboard = { active = true },
  statusline = { active = true },
  bufferline = { active = true },
  devicons = { active = true },
  git_signs = { active = true },
  indent_line = { active = true },
  -- completion
  which_key = { active = true },
  plenary = { active = true },
  popup = { active = true },
  telescope = { active = true },
  cmp = { active = true },
  vsnip = { active = true },
  emmet = { active = false },
  friendly_snippets = { active = true },
  telescope_fzf = { active = true },
  telescope_ui_select = { active = true },
  telescope_tmux = { active = true },
  telescope_frecency = { active = true },
}
