return {
  servers = {
    "clangd",
    "cssls",
    "cmake",
    "dockerls",
    "elixirls",
    "emmet_ls",
    "gopls",
    "graphql",
    "html",
    "jsonls",
    "sumneko_lua",
    "pyright",
    "rust_analyzer",
    "bashls",
    "vimls",
    "yamlls",
    "tsserver",
    "eslint",
  },
  colors = {
    error = rvim.style.palette.pale_red,
    warn = rvim.style.palette.dark_orange,
    info = rvim.style.palette.bright_blue,
    hint = rvim.style.palette.teal,
  },
  completion = {
    item_kind = {
      "   (Text) ",
      "   (Method)",
      " ƒ  (Function)",
      "   (Constructor)",
      " ﴲ  (Field)",
      "   (Variable)",
      "   (Class)",
      " ﰮ  (Interface)",
      "   (Module)",
      " 襁 (Property)",
      "   (Unit)",
      "   (Value)",
      " 了 (Enum)",
      "   (Keyword)",
      "   (Snippet)",
      "   (Color)",
      "   (File)",
      "   (Reference)",
      "   (Folder)",
      "   (EnumMember)",
      "   (Constant)",
      " ﳤ  (Struct)",
      " 鬒 (Event)",
      "   (Operator)",
      "   (TypeParameter)",
    },
  },
  diagnostics = {
    signs = {
      active = false,
      values = {
        { name = "LspDiagnosticsSignError", text = "" },
        { name = "LspDiagnosticsSignWarning", text = "" },
        { name = "LspDiagnosticsSignInformation", text = "" },
        { name = "LspDiagnosticsSignHint", text = "" },
      },
    },
    virtual_text = {
      prefix = "",
      spacing = 2,
    },
    underline = true,
    update_in_insert = false,
    severity_sort = false,
  },
  null_ls = {
    setup = {
      -- root_dir = require("lspconfig").util.root_pattern("Makefile", ".git", "node_modules"),
    },
  },
  override = {
    "angularls",
    "ansiblels",
    "denols",
    "ember",
    "jedi_language_server",
    "pylsp",
    "rome",
    "sqlls",
    "sqls",
    "stylelint_lsp",
    "tailwindcss",
    "volar",
  },
  automatic_servers_installation = true,
  on_attach_callback = nil,
  on_init_callback = nil,
  document_highlight = true,
  code_lens_refresh = true,
  hover_diagnostics = true,
  lint_on_save = false,
  popup_border = "single",
}
