local home = os.getenv('HOME')
vim.g.dashboard_preview_command = 'cat'
vim.g.dashboard_preview_pipeline = 'lolcat'
vim.g.dashboard_preview_file = home .. '/.config/nvim/static/pokemon.txt'
vim.g.dashboard_preview_file_height = 14
vim.g.dashboard_preview_file_width = 80
vim.g.dashboard_default_executive = 'telescope'
vim.g.dashboard_custom_section = {
  last_session = {
    description = {'  Recently laset session                  SPC s l'},
    command =  'SessionLoad'},
  find_history = {
    description = {'  Recently opened files                   SPC f h'},
    command =  'DashboardFindHistory'},
  find_file  = {
    description = {'  Find  File                              SPC f f'},
    command = 'DashboardFindFile'},
  new_file = {
    description = {'  New   File                              SPC t f'},
    command =  'DashboardNewFile'},
  find_word = {
    description = {'  Find  word                              SPC f w'},
    command = 'DashboardFindWord'},
  --[[ find_dotfiles = {
    description = {'  Open Personal dotfiles                  SPC f d'},
    command = 'Telescope dotfiles path=' .. home ..'/.dotfiles'},
  go_source = {
    description = {'  Find Go Source Code                     SPC f s'},
    command = 'Telescope gosource'}, ]]
}
