local P = rvim.palette
local util = require "zephyr.util"
local darker_bg = util.alter_color(P.bg, -20)

return {
  Normal = { fg = P.fg, bg = darker_bg },
  NormalNC = { fg = P.fg, bg = P.none },
  Terminal = { fg = P.fg, bg = P.bg },
  SignColumn = { fg = P.fg, bg = darker_bg },
  FoldColumn = { fg = P.fg_alt, bg = P.black },
  VertSplit = { fg = P.dull_blue, bg = darker_bg },
  MsgArea = { bg = darker_bg },
  MsgSeparator = { guifg = P.base6, guibg = darker_bg },
  Folded = { fg = P.grey, bg = P.highlight_bg },
  EndOfBuffer = { fg = P.bg, bg = P.none },
  IncSearch = { fg = P.bg, bg = P.orange, style = P.none },
  Search = { fg = P.bg, bg = P.orange },
  Conceal = { fg = P.grey, bg = P.none },
  Cursor = { fg = P.none, bg = P.none, style = "reverse" },
  vCursor = { fg = P.none, bg = P.none, style = "reverse" },
  iCursor = { fg = P.none, bg = P.none, style = "reverse" },
  lCursor = { fg = P.none, bg = P.none, style = "reverse" },
  ColorColumn = { fg = P.none, bg = P.bg },
  CursorIM = { fg = P.none, bg = P.none, style = "reverse" },
  CursorColumn = { fg = P.none, bg = P.dark_alt },
  CursorLine = { fg = P.none, bg = P.dark_alt },
  LineNr = { fg = P.base5, bg = P.none },
  qfLineNr = { fg = P.cyan },
  qfFileName = { fg = P.yellowgreen },
  CursorLineNr = { fg = P.pink, style = "bold" },
  netrwDir = { fg = P.pink },
  DiffAdd = { fg = P.black, bg = P.dark_green },
  DiffChange = { fg = P.black, bg = P.yellow },
  DiffDelete = { fg = P.black, bg = P.red },
  DiffText = { fg = P.black, bg = P.fg },
  Directory = { fg = P.blue, bg = P.none },
  ErrorMsg = { fg = P.pale_red, bg = P.none, style = "bold" },
  WarningMsg = { fg = P.dark_orange, bg = P.none, style = "bold" },
  ModeMsg = { fg = P.fg, bg = P.none, style = "bold" },
  MatchParen = { fg = P.red, bg = P.none },
  NonText = { fg = P.bg },
  Whitespace = { fg = P.base4 },
  SpecialKey = { fg = P.bg },
  Pmenu = { fg = P.fg, bg = P.bg_popup },
  PmenuSel = { fg = P.base0, bg = P.blue },
  PmenuSelBold = { fg = P.base0, g = P.blue },
  PmenuSbar = { fg = P.none, bg = P.base4 },
  PmenuThumb = { bg = P.light_green },
  WildMenu = { fg = P.fg, bg = P.green },
  Question = { fg = P.yellow },
  NormalFloat = { fg = P.base8, bg = P.bg_highlight },
  TabLineFill = { bg = P.bg, style = P.none },
  TabLineSel = { bg = P.dark_alt },
  StatusLine = { fg = P.base8, bg = P.base2, style = P.none },
  StatusLineNC = { fg = P.grey, bg = P.base2, style = P.none },
  SpellBad = { fg = P.red, bg = P.none, style = "undercurl" },
  SpellCap = { fg = P.blue, bg = P.none, style = "undercurl" },
  SpellLocal = { fg = P.cyan, bg = P.none, style = "undercurl" },
  SpellRare = { fg = P.violet, bg = P.none, style = "undercurl" },
  Visual = { fg = P.black, bg = P.bracket },
  VisualNOS = { fg = P.black, bg = P.bracket },
  QuickFixLine = { fg = P.black },
  Debug = { fg = P.orange },
  debugBreakpoint = { fg = P.bg, bg = P.red },

  Boolean = { fg = P.orange },
  Number = { fg = P.brown },
  Float = { fg = P.brown },
  PreProc = { fg = P.violet },
  PreCondit = { fg = P.violet },
  Include = { fg = P.violet },
  Define = { fg = P.violet },
  Conditional = { fg = P.magenta },
  Repeat = { fg = P.magenta },
  Keyword = { fg = P.green },
  Typedef = { fg = P.red },
  Exception = { fg = P.red },
  Statement = { fg = P.red },
  Error = { fg = P.red },
  StorageClass = { fg = P.orange },
  Tag = { fg = P.orange },
  Label = { fg = P.orange },
  Structure = { fg = P.orange },
  Operator = { fg = P.redwine },
  Title = { fg = P.orange, style = "bold" },
  Special = { fg = P.yellow },
  SpecialChar = { fg = P.yellow },
  Type = { fg = P.teal },
  Function = { fg = P.yellow },
  String = { fg = P.light_green },
  Character = { fg = P.green },
  Constant = { fg = P.cyan },
  Macro = { fg = P.cyan },
  Identifier = { fg = P.blue },

  Comment = { fg = P.base6 },
  SpecialComment = { fg = P.grey },
  Todo = { fg = P.orange, style = "italic" },
  Delimiter = { fg = P.fg },
  Ignore = { fg = P.grey },
  Underlined = { fg = P.none, style = "underline" },
}
