local P = rvim.palette
local util = require('user.utils.highlights')

local function fade(color)
  return util.alter_color(color, -80)
end

return {
  vimCommentTitle = { fg = P.grey, bold = true },
  vimLet = { fg = P.orange },
  vimVar = { fg = P.cyan },
  vimFunction = { fg = P.redwine },
  vimIsCommand = { fg = P.fg },
  vimCommand = { fg = P.blue },
  vimNotFunc = { fg = P.violet, bold = true },
  vimUserFunc = { fg = P.yellow, bold = true },
  vimFuncName = { fg = P.yellow, bold = true },

  diffAdded = { fg = P.dark_green },
  diffRemoved = { fg = P.red },
  diffChanged = { fg = P.blue },
  diffOldFile = { fg = P.yellow },
  diffNewFile = { fg = P.orange },
  diffFile = { fg = P.aqua },
  diffLine = { fg = P.grey },
  diffIndexLine = { fg = P.violet },
  diffBDiffer = { link = 'WarningMsg' },
  diffCommon = { link = 'WarningMsg' },
  diffDiffer = { link = 'WarningMsg' },
  diffIdentical = { link = 'WarningMsg' },
  diffIsA = { link = 'WarningMsg' },
  diffNoEOL = { link = 'WarningMsg' },
  diffOnly = { link = 'WarningMsg' },

  gitcommitSummary = { fg = P.red },
  gitcommitUntracked = { fg = P.grey },
  gitcommitDiscarded = { fg = P.grey },
  gitcommitSelected = { fg = P.grey },
  gitcommitUnmerged = { fg = P.grey },
  gitcommitOnBranch = { fg = P.grey },
  gitcommitArrow = { fg = P.grey },
  gitcommitFile = { fg = P.dark_green },

  GitGutterAdd = { fg = P.dark_green },
  GitGutterChange = { fg = P.blue },
  GitGutterDelete = { fg = P.red },
  GitGutterChangeDelete = { fg = P.violet },

  GitSignsAdd = { fg = P.dark_green },
  GitSignsChange = { fg = P.blue },
  GitSignsDelete = { fg = P.red },
  GitSignsAddNr = { fg = P.dark_green },
  GitSignsChangeNr = { fg = P.blue },
  GitSignsDeleteNr = { fg = P.red },
  GitSignsAddLn = { bg = P.dark_grey },
  GitSignsChangeLn = { bg = P.bg_highlight },
  GitSignsDeleteLn = { bg = P.bg },

  SignifySignAdd = { fg = P.dark_green },
  SignifySignChange = { fg = P.blue },
  SignifySignDelete = { fg = P.red },

  dbui_tables = { fg = P.blue },

  DiagnosticError = { fg = P.error_red },
  DiagnosticWarning = { fg = P.dark_orange },
  DiagnosticInfo = { fg = P.blue },
  DiagnosticHint = { fg = P.darker_green },

  DiagnosticSignError = { fg = P.error_red },
  DiagnosticSignWarn = { fg = P.dark_orange },
  DiagnosticSignInfo = { fg = P.blue },
  DiagnosticSignHint = { fg = P.darker_green },

  DiagnosticFloatingError = { fg = P.error_red },
  DiagnosticFloatingWarn = { fg = P.dark_orange },
  DiagnosticFloatingInfo = { fg = P.blue },
  DiagnosticFloatingHint = { fg = P.darker_green },

  DiagnosticUnderlineError = { undercurl = true, sp = P.error_red },
  DiagnosticUnderlineWarn = { undercurl = true, sp = P.dark_orange },
  DiagnosticUnderlineInfo = { undercurl = true, sp = P.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = P.darker_green },

  DiagnosticVirtualTextError = { fg = P.error_red, bg = fade(P.pale_red) },
  DiagnosticVirtualTextWarn = { fg = P.dark_orange, bg = fade(P.dark_orange) },
  DiagnosticVirtualTextInfo = { fg = P.pale_blue, bg = fade(P.pale_blue) },
  DiagnosticVirtualTextHint = { fg = P.dark_green, bg = fade(P.darker_green) },

  LspReferenceRead = { bg = P.base4 },
  LspReferenceText = { bg = P.base4 },
  LspReferenceWrite = { bg = P.base4 },

  TroubleCount = { bg = P.dark_alt, fg = P.pink },
  TroubleFile = { fg = P.blue, bold = true },
  TroubleTextError = { fg = P.red },
  TroubleTextWarning = { fg = P.yellow },
  TroubleTextInformation = { fg = P.blue },
  TroubleTextHint = { fg = P.teal },

  BqfPreviewBorder = { fg = P.darker_blue },
  BqfSign = { fg = P.red },
  BqfPreviewRange = { fg = P.cyan },
  BqfPreviewCursor = { fg = P.yellowgreen },

  CursorWord0 = { bg = P.cursor_bg },
  CursorWord1 = { bg = P.none },
  CursorWord = { bg = P.none },

  NvimTreeFolderIcon = { fg = P.blue },
  NvimTreeIndentMarker = { fg = P.base6 },
  NvimTreeFolderName = { fg = P.blue },
  NvimTreeOpenedFolderName = { fg = P.base5 },
  NvimTreeImageFile = { fg = P.pink },
  NvimTreeSpecialFile = { fg = P.orange },

  NvimTreeGitStaged = { fg = P.dark_green },
  NvimTreeCursorLine = { bg = P.red },
  NvimTreeGitNew = { fg = P.sign_add },
  NvimTreeGitDirty = { fg = P.dark_green },
  NvimTreeGitDeleted = { fg = P.sign_delete },
  NvimTreeGitMerge = { fg = P.sign_change },
  NvimTreeGitRenamed = { fg = P.sign_change },

  NvimTreeLspDiagnosticsError = { fg = P.error_red },
  NvimTreeLspDiagnosticsWarning = { fg = P.dark_orange },
  NvimTreeLspDiagnosticsInformation = { fg = P.blue },
  NvimTreeLspDiagnosticsHint = { fg = P.dark_green },

  NvimTreeSymlink = { fg = P.cyan },
  NvimTreeExecFile = { fg = P.green },
  NvimTreeEmptyFolderName = { fg = P.base5 },

  NeoTreeGitAdded = { fg = P.sign_add },
  NeoTreeGitConflict = { fg = P.sign_delete },
  NeoTreeGitDeleted = { fg = P.sign_delete },
  NeoTreeGitIgnored = { fg = P.base5 },
  NeoTreeGitModified = { fg = P.sign_change },
  NeoTreeGitUntracked = { fg = P.sign_add },
  NeoTreeHiddenByName = { fg = P.base5 },

  TelescopeNormal = { fg = P.fg },
  TelescopeBorder = { fg = P.darker_blue, bg = P.darker_bg },
  TelescopeResultsBorder = { fg = P.darker_blue, bg = P.darker_bg },
  TelescopePromptBorder = { fg = P.darker_blue, bg = P.darker_bg },
  TelescopePreviewBorder = { fg = P.blue, bg = P.darker_bg },
  TelescopeMatching = { fg = P.cyan },
  TelescopeSelection = { fg = P.light_green },
  TelescopeSelectionCaret = { fg = P.light_green },
  TelescopeMultiSelection = { fg = P.light_green },
  TelescopePromptPrefix = { fg = P.light_green },

  FloatermBorder = { fg = P.blue, bg = P.bg },

  DashboardShortCut = { fg = P.darker_blue },
  DashboardHeader = { fg = P.blue },
  DashboardCenter = { fg = P.blue },
  DashboardFooter = { fg = P.dark_cyan },

  WhichKey = { fg = P.pink },
  WhichKeyName = { fg = P.yellow },
  WhichKeyTrigger = { fg = P.black },
  WhichKeyFloat = { fg = P.red, bg = P.darker_bg },
  WhichKeySeperator = { fg = P.yellowgreen },
  WhichKeyGroup = { fg = P.pale_blue },
  WhichKeyDesc = { fg = P.dark_cyan },

  NotifyERRORBorder = { fg = P.error_red },
  NotifyWARNBorder = { fg = P.dark_orange },
  NotifyINFOBorder = { fg = P.blue },
  NotifyDEBUGBorder = { fg = P.purple_test },
  NotifyTRACEBorder = { fg = P.pink },
  NotifyERRORIcon = { fg = P.error_red },
  NotifyWARNIcon = { fg = P.dark_orange },
  NotifyINFOIcon = { fg = P.blue },
  NotifyDEBUGIcon = { fg = P.purple_test },
  NotifyTRACEIcon = { fg = P.pink },
  NotifyERRORTitle = { fg = P.error_red },
  NotifyWARNTitle = { fg = P.dark_orange },
  NotifyINFOTitle = { fg = P.blue },
  NotifyDEBUGTitle = { fg = P.purple_test },
  NotifyTRACETitle = { fg = P.pink },
  NotifyERRORBody = { fg = P.fg },
  NotifyWARNBody = { fg = P.fg },
  NotifyINFOBody = { fg = P.fg },
  NotifyDEBUGBody = { fg = P.fg },
  NotifyTRACEBody = { fg = P.fg },

  Winbar = { fg = P.base5 },
  WinbarCrumb = { fg = P.comment },
  WinbarCurrent = { fg = P.comment },
  WinbarDirectory = { fg = P.comment },

  CmpItemAbbrMatch = { fg = P.light_green },
  CmpItemMenu = { fg = P.base5 },
}
