local P = rvim.palette
local util = require "zephyr.util"
local darker_bg = util.alter_color(P.bg, -20)

return {
  TSFunction = { fg = P.cyan },
  TSComment = { fg = P.dark },
  TSMethod = { fg = P.cyan },
  TSKeywordFunction = { fg = P.red },
  TSProperty = { fg = P.yellow },
  TSType = { fg = P.teal },
  TSVariable = { fg = P.blue },
  TSPunctBracket = { fg = P.bracket },

  vimCommentTitle = { fg = P.grey, style = "bold" },
  vimLet = { fg = P.orange },
  vimVar = { fg = P.cyan },
  vimFunction = { fg = P.redwine },
  vimIsCommand = { fg = P.fg },
  vimCommand = { fg = P.blue },
  vimNotFunc = { fg = P.violet, style = "bold" },
  vimUserFunc = { fg = P.yellow, style = "bold" },
  vimFuncName = { fg = P.yellow, style = "bold" },

  diffAdded = { fg = P.dark_green },
  diffRemoved = { fg = P.red },
  diffChanged = { fg = P.blue },
  diffOldFile = { fg = P.yellow },
  diffNewFile = { fg = P.orange },
  diffFile = { fg = P.aqua },
  diffLine = { fg = P.grey },
  diffIndexLine = { fg = P.violet },
  diffBDiffer = { link = "WarningMsg", force = true },
  diffCommon = { link = "WarningMsg", force = true },
  diffDiffer = { link = "WarningMsg", force = true },
  diffIdentical = { link = "WarningMsg", force = true },
  diffIsA = { link = "WarningMsg", force = true },
  diffNoEOL = { link = "WarningMsg", force = true },
  diffOnly = { link = "WarningMsg", force = true },

  gitcommitSummary = { fg = P.red },
  gitcommitUntracked = { fg = P.grey },
  gitcommitDiscarded = { fg = P.grey },
  gitcommitSelected = { fg = P.grey },
  gitcommitUnmerged = { fg = P.grey },
  gitcommitOnBranch = { fg = P.grey },
  gitcommitArrow = { fg = P.grey },
  gitcommitFile = { fg = P.dark_green },

  GitGutterAdd = { fg = P.dark_green },
  GitGutterChange = { fg = P.blue },
  GitGutterDelete = { fg = P.red },
  GitGutterChangeDelete = { fg = P.violet },

  GitSignsAdd = { fg = P.dark_green },
  GitSignsChange = { fg = P.blue },
  GitSignsDelete = { fg = P.red },
  GitSignsAddNr = { fg = P.dark_green },
  GitSignsChangeNr = { fg = P.blue },
  GitSignsDeleteNr = { fg = P.red },
  GitSignsAddLn = { bg = P.bg_popup },
  GitSignsChangeLn = { bg = P.bg_highlight },
  GitSignsDeleteLn = { bg = P.bg },

  SignifySignAdd = { fg = P.dark_green },
  SignifySignChange = { fg = P.blue },
  SignifySignDelete = { fg = P.red },

  dbui_tables = { fg = P.blue },

  DiagnosticError = { fg = P.pale_red },
  DiagnosticWarning = { fg = P.dark_orange },
  DiagnosticInfo = { fg = P.blue },
  DiagnosticHint = { fg = P.teal },

  LspDiagnosticsError = { fg = P.pale_red },
  LspDiagnosticsWarning = { fg = P.dark_orange },
  LspDiagnosticsInformation = { fg = P.blue },
  LspDiagnosticsHint = { fg = P.teal },

  DiagnosticsSignErrorLine = { fg = P.pale_red },
  DiagnosticsSignWarnLine = { fg = P.dark_orange },
  DiagnosticsSignInfoLine = { fg = P.blue },
  DiagnosticsSignHintLine = { fg = P.teal },

  DiagnosticSignError = { fg = P.pale_red },
  DiagnosticSignWarn = { fg = P.dark_orange },
  DiagnosticSignInfo = { fg = P.blue },
  DiagnosticSignHint = { fg = P.teal },

  DiagnosticFloatingError = { fg = P.pale_red },
  DiagnosticFloatingWarn = { fg = P.dark_orange },
  DiagnosticFloatingInfo = { fg = P.blue },
  DiagnosticFloatingHint = { fg = P.teal },

  LspDiagnosticsFloatingError = { fg = P.pale_red },
  LspDiagnosticsFloatingWarning = { fg = P.dark_orange },
  LspDiagnosticsFloatingInformation = { fg = P.blue },
  LspDiagnosticsFloatingHint = { fg = P.teal },

  DiagnosticUnderlineError = { style = "undercurl", sp = P.pale_red },
  DiagnosticUnderlineWarn = { style = "undercurl", sp = P.dark_orange },
  DiagnosticUnderlineInfo = { style = "undercurl", sp = P.blue },
  DiagnosticUnderlineHint = { style = "undercurl", sp = P.teal },

  LspDiagnosticsVirtualTextError = { fg = P.pale_red },
  LspDiagnosticsVirtualTextWarning = { fg = P.dark_orange },
  LspDiagnosticsVirtualTextInformation = { fg = P.blue },
  LspDiagnosticsVirtualTextHint = { fg = P.teal },

  DiagnosticVirtualTextError = { fg = P.pale_red, bg = util.alter_color(P.pale_red, -80) },
  DiagnosticVirtualTextWarn = { fg = P.dark_orange, bg = util.alter_color(P.dark_orange, -80) },
  DiagnosticVirtualTextInfo = { fg = P.pale_blue, bg = util.alter_color(P.pale_blue, -80) },
  DiagnosticVirtualTextHint = { fg = P.teal, bg = util.alter_color(P.teal, -80) },

  LspReferenceRead = { bg = P.base4 },
  LspReferenceText = { bg = P.base4 },
  LspReferenceWrite = { bg = P.base4 },

  TroubleCount = { bg = P.highlight_bg, fg = P.magenta },
  TroubleFile = { fg = P.blue, style = "bold" },
  TroubleTextError = { fg = P.red },
  TroubleTextWarning = { fg = P.yellow },
  TroubleTextInformation = { fg = P.blue },
  TroubleTextHint = { fg = P.teal },

  BqfPreviewBorder = { fg = P.blue },
  BqfSign = { fg = P.red },
  BqfPreviewRange = "fg = P.red",

  CursorWord0 = { bg = P.cursor_bg },
  CursorWord1 = { bg = P.none },
  CursorWord = { bg = P.none },

  -- NvimTreeNormal = { bg = P.alt_bg },
  -- NvimTreeNormalNC = { bg = P.alt_bg },
  -- NvimTreeSignColumn = { bg = P.alt_bg },
  -- NvimTreeEndOfBuffer = { bg = P.alt_bg },
  NvimTreeFolderIcon = { fg = P.blue },
  NvimTreeIndentMarker = { fg = P.base6 },
  NvimTreeVertSplit = { fg = P.blue, bg = P.yellow },
  NvimTreeImageFile = { fg = P.purple },
  NvimTreeSpecialFile = { fg = P.orange },
  NvimTreeGitStaged = { fg = P.sign_add },
  NvimTreeCursorLine = { bg = P.red },
  NvimTreeGitNew = { fg = P.sign_add },
  NvimTreeGitDirty = { fg = P.sign_add },
  NvimTreeGitDeleted = { fg = P.sign_delete },
  NvimTreeGitMerge = { fg = P.sign_change },
  NvimTreeGitRenamed = { fg = P.sign_change },
  NvimTreeSymlink = { fg = P.cyan },
  NvimTreeExecFile = { fg = P.green },
  NvimTreeFolderName = { fg = P.blue },
  NvimTreeEmptyFolderName = { fg = P.base5 },
  NvimTreeRootFolder = { fg = P.base5, style = "bold" },
  NvimTreeOpenedFolderName = { fg = P.base5 },

  TelescopeNormal = { fg = P.fg },
  TelescopeBorder = { fg = P.blue, bg = darker_bg },
  TelescopeResultsBorder = { fg = P.blue, bg = darker_bg },
  TelescopePromptBorder = { fg = P.blue, bg = darker_bg },
  TelescopePreviewBorder = { fg = P.magenta, bg = darker_bg },
  TelescopeMatching = { fg = P.yellowgreen, style = "bold" },
  TelescopeSelection = { fg = P.cyan, style = "bold" },
  TelescopeSelectionCaret = { fg = P.yellow },
  TelescopeMultiSelection = { fg = P.light_green },
  TelescopePromptPrefix = { fg = P.yellow },

  FloatermBorder = { fg = P.blue, bg = P.bg },

  DashboardShortCut = { fg = P.darker_blue },
  DashboardHeader = { fg = P.blue },
  DashboardCenter = { fg = P.blue },
  DashboardFooter = { fg = P.dark_cyan, style = "bold" },

  WhichKey = { fg = P.pink },
  WhichKeyName = { fg = P.yellow },
  WhichKeyTrigger = { fg = P.black },
  WhichKeyFloating = { fg = P.red },
  WhichKeySeperator = { fg = P.yellowgreen },
  WhichKeyGroup = { fg = P.pale_blue },
  WhichKeyDesc = { fg = P.dark_cyan },
}
