return {
  border = {
    line = {
      { "🭽", "FloatBorder" },
      { "▔", "FloatBorder" },
      { "🭾", "FloatBorder" },
      { "▕", "FloatBorder" },
      { "🭿", "FloatBorder" },
      { "▁", "FloatBorder" },
      { "🭼", "FloatBorder" },
      { "▏", "FloatBorder" },
    },
  },
  icons = {
    git = {
      add = "",
      mod = "",
      remove = "",
      ignore = "",
      rename = "",
      diff = "",
      repo = "",
    },
    documents = {
      file = "",
      files = "",
      folder = "",
      open_folder = "",
    },
    type = {
      array = "",
      number = "",
      object = "",
    },
    misc = {
      dap_red = "🛑",
      dap_hollow = "🟢",
      bug = "",
      bug_alt = "",
      question = "",
      lock = "",
      circle = "",
      project = "",
      dashboard = "",
      history = "",
      comment = "",
      robot = "ﮧ",
      lightbulb = "",
      search = "",
      code = "",
      telescope = "",
      gear = "",
      package = "",
      list = "",
      sign_in = "",
      check = "",
      fire = "",
      note = "",
      bookmark = "",
      pencil = "",
      chevron_right = "",
      chevron_right_alt = "❯",
      double_chevron_right = "»",
      table = "",
      calendar = "",
    },
    kind = {
      Class = "", -- '',
      Color = " ",
      Constant = "", -- '',ﲀ
      Constructor = " ",
      Enum = "練",
      EnumMember = " ",
      Event = " ",
      Field = "", -- '',
      File = "",
      Folder = " ",
      Function = " ",
      Interface = "ﰮ ",
      Keyword = "", -- '',
      Method = " ",
      Module = " ",
      Operator = "",
      Property = " ",
      Reference = "", -- '',
      Snippet = "", -- '', '',
      Struct = "", -- 'פּ',
      Text = " ",
      TypeParameter = " ",
      Unit = "塞",
      Value = " ",
      Variable = "", -- '',
    },
  },
}
